version: '3.8'

services:
  nextjs:
    build: .
    container_name: iptv-nextjs
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: iptv-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs

  certbot:
    image: certbot/certbot
    container_name: iptv-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./html:/var/www/html
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done"

volumes:
  certbot-etc:
  certbot-var:
